name: "@title@"
rundeckPluginVersion: 1.2
author: "@author@"
date: "@date@"
version: "@version@"
url: "@url@"
providers:
    - name: "@name@"
      service: UI
      title: "@title@"
      description: "@description@"
      plugin-type: ui
      ui:
        - pages: '*'
          scripts:
            - js/init.js
            - js/main.js
          styles:
            - css/rainbow.css